### ISSUE TITLE
Probems with s2i builds on OpenShift 3.7 

### ISSUE THREAD

**Issue by rhuss** [fabric8io/fabric8-maven-plugin#1221]
### Description

When doing a s2i build on OpenShift 3.7 the following error is shown on the output:

```
[INFO] F8: Waiting for build syndesis-server-s2i-2 to complete...
[INFO] F8: {"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"container \"sti-build\" in pod \"syndesis-server-s2i-2-build\" is waiting to start: PodInitializing","reason":"BadRequest","code":400}
[INFO] Current reconnect backoff is 1000 milliseconds (T0)
[INFO] Current reconnect backoff is 2000 milliseconds (T1)
[INFO] Current reconnect backoff is 4000 milliseconds (T2)
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
[INFO] Current reconnect backoff is 16000 milliseconds (T4)
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Build syndesis-server-s2i-2 Complete
[WARNING] Executor didn't terminate in time after shutdown in close(), killing it in: io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager@7be2e53f
[INFO] F8: Found tag on ImageStream syndesis-server tag: sha256:b9b41221778762d2eb67789ba4ad1b0c8e051faf0b82ccf42bc4adc8a1487359
```

The build still succeeds but the error message is irritating.

### Info

* f-m-p version : 3.5.33
* Maven version (`mvn -v`) :
```
Apache Maven 3.5.2 (138edd61fd100ec658bfa2d307c43b76940a5d7d; 2017-10-18T09:58:13+02:00)
Maven home: /Users/roland/.m2/wrapper/dists/apache-maven-3.5.2-bin/28qa8v9e2mq69covern8vmdkj0/apache-maven-3.5.2
Java version: 1.8.0_152, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_152.jdk/Contents/Home/jre
Default locale: en_DE, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.2", arch: "x86_64", family: "mac"
```
* Kubernetes / OpenShift setup and version :minishift v1.13.1+75352e5

**Comment by rohanKanojia** [comment]
Hi @rhuss ,
This was a bug in 3.5.33, But it was fixed in #1132 . Could you try with some other version of fabric8-maven-plugin (i.e. 3.5.34/3.5.35)?

**Comment by rhuss** [comment]
yeah, makes sense. Thanks for the heads up !

**Comment by oscerd** [comment]
We still see the WatchHTTPManager warning with 3.5.38

```
[INFO] F8: Using OpenShift build with strategy S2I
[INFO] F8: Running generator spring-boot
[INFO] F8: spring-boot: Using Docker image fabric8/s2i-java:2.1 as base / builder
[INFO] Copying files to /home/oscerd/workspace/jboss-fuse/syndesis/app/server/runtime/target/docker/syndesis/syndesis-server/latest/build/maven
[INFO] Building tar: /home/oscerd/workspace/jboss-fuse/syndesis/app/server/runtime/target/docker/syndesis/syndesis-server/latest/tmp/docker-build.tar
[INFO] F8: [syndesis/syndesis-server:latest] "spring-boot": Created docker source tar /home/oscerd/workspace/jboss-fuse/syndesis/app/server/runtime/target/docker/syndesis/syndesis-server/latest/tmp/docker-build.tar
[INFO] F8: Creating BuildServiceConfig syndesis-server-s2i for Source build
[INFO] F8: Creating ImageStream syndesis-server
[INFO] F8: Starting Build syndesis-server-s2i
[INFO] F8: Waiting for build syndesis-server-s2i-1 to complete...
[INFO] Current reconnect backoff is 1000 milliseconds (T0)
[INFO] Current reconnect backoff is 2000 milliseconds (T1)
[INFO] Current reconnect backoff is 4000 milliseconds (T2)
[INFO] Current reconnect backoff is 8000 milliseconds (T3)
[INFO] Current reconnect backoff is 16000 milliseconds (T4)
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: ==================================================================
[INFO] F8: Starting S2I Java Build .....
[INFO] F8: S2I binary build from fabric8-maven-plugin detected
[INFO] F8: Copying binaries from /tmp/src/maven to /deployments ...
[INFO] F8: Checking for SpringBoot archive...
[INFO] F8: Found runtime.jar...
[INFO] F8: ... done
[INFO] F8: 
[INFO] F8: Pushing image 172.30.1.1:5000/myproject/syndesis-server:latest ...
[INFO] F8: Pushed 0/26 layers, 0% complete
[INFO] F8: Pushed 1/26 layers, 15% complete
[INFO] F8: Pushed 2/26 layers, 15% complete
[INFO] F8: Pushed 3/26 layers, 15% complete
[INFO] F8: Pushed 4/26 layers, 15% complete
[INFO] F8: Pushed 5/26 layers, 19% complete
[INFO] F8: Pushed 6/26 layers, 23% complete
[INFO] F8: Pushed 7/26 layers, 27% complete
[INFO] F8: Pushed 8/26 layers, 31% complete
[INFO] F8: Pushed 9/26 layers, 35% complete
[INFO] F8: Pushed 10/26 layers, 39% complete
[INFO] F8: Pushed 11/26 layers, 43% complete
[INFO] F8: Pushed 12/26 layers, 48% complete
[INFO] F8: Pushed 13/26 layers, 51% complete
[INFO] F8: Pushed 14/26 layers, 55% complete
[INFO] F8: Pushed 15/26 layers, 60% complete
[INFO] F8: Pushed 16/26 layers, 64% complete
[INFO] F8: Pushed 17/26 layers, 68% complete
[INFO] F8: Pushed 18/26 layers, 74% complete
[INFO] F8: Pushed 19/26 layers, 77% complete
[INFO] F8: Pushed 20/26 layers, 80% complete
[INFO] F8: Pushed 21/26 layers, 84% complete
[INFO] F8: Pushed 22/26 layers, 90% complete
[INFO] F8: Pushed 23/26 layers, 92% complete
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Pushed 24/26 layers, 96% complete
[INFO] F8: Pushed 25/26 layers, 98% complete
[INFO] F8: Pushed 26/26 layers, 100% complete
[INFO] F8: Push successful
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Build syndesis-server-s2i-1 Complete
[WARNING] Executor didn't terminate in time after shutdown in close(), killing it in: io.fabric8.kubernetes.client.dsl.internal.WatchHTTPManager@29a9f925
[INFO] F8: Found tag on ImageStream syndesis-server tag: sha256:df90bb569738ae14a3fdfbf4b226605510e73eab5768d38e5c537f465c0ef9ef
[INFO] F8: ImageStream syndesis-server written to /home/oscerd/workspace/jboss-fuse/syndesis/app/server/runtime/target/server-runtime-is.yml
```

@rohanKanojia it looks like you're talking about reconnect backoff, while we are talking about the Warning coming from WatchHTTPManager...

**Comment by piyush1594** [comment]
@oscerd Earlier only this reconnect warning error was shown, no build logs were shown and says build is completed.

Now this has been fixed, now this will show build logs also the reconnect warnings.

**Comment by piyush1594** [comment]
Difference is 
```
[INFO] F8: Pushing image 172.30.1.1:5000/myproject/syndesis-server:latest ...
[INFO] F8: Pushed 0/26 layers, 0% complete
[INFO] F8: Pushed 1/26 layers, 15% complete
[INFO] F8: Pushed 2/26 layers, 15% complete
[INFO] F8: Pushed 3/26 layers, 15% complete
[INFO] F8: Pushed 4/26 layers, 15% complete
[INFO] F8: Pushed 5/26 layers, 19% complete
[INFO] F8: Pushed 6/26 layers, 23% complete
[INFO] F8: Pushed 7/26 layers, 27% complete
[INFO] F8: Pushed 8/26 layers, 31% complete
[INFO] F8: Pushed 9/26 layers, 35% complete
[INFO] F8: Pushed 10/26 layers, 39% complete
[INFO] F8: Pushed 11/26 layers, 43% complete
[INFO] F8: Pushed 12/26 layers, 48% complete
[INFO] F8: Pushed 13/26 layers, 51% complete
[INFO] F8: Pushed 14/26 layers, 55% complete
[INFO] F8: Pushed 15/26 layers, 60% complete
[INFO] F8: Pushed 16/26 layers, 64% complete
[INFO] F8: Pushed 17/26 layers, 68% complete
[INFO] F8: Pushed 18/26 layers, 74% complete
[INFO] F8: Pushed 19/26 layers, 77% complete
[INFO] F8: Pushed 20/26 layers, 80% complete
[INFO] F8: Pushed 21/26 layers, 84% complete
[INFO] F8: Pushed 22/26 layers, 90% complete
[INFO] F8: Pushed 23/26 layers, 92% complete
[INFO] Current reconnect backoff is 32000 milliseconds (T5)
[INFO] F8: Pushed 24/26 layers, 96% complete
[INFO] F8: Pushed 25/26 layers, 98% complete
[INFO] F8: Pushed 26/26 layers, 100% complete
[INFO] F8: Push successful
```

**Comment by oscerd** [comment]
So #1132 didn't solve the Warning message

**Comment by piyush1594** [comment]
It was about the missing build logs

**Comment by rohanKanojia** [comment]
Sorry, my bad. I misinterpreted it for the logs bug as I saw that as the only error message; Roland didn't mention any warning message, that's why I assumed.

**Comment by rhuss** [comment]
ah, ok. whats about the other `INFO` level log message about the reconnect backoff ? @iocanel any ideas ?

**Comment by rhuss** [comment]
Actually for me its more like a debug message, nothing which we might worry about and for sure not an information which useful for the user, as its an implementation detail.

So you still could see this with mvn -X if this would be on debug level. btw, you dont see such details when running with `oc build` so we shouldnt show this here, too.

**Comment by iocanel** [comment]
@rhuss: when using watcher, if for any reason the connection is dropped, the client tries to recoonect. Recoonection attempts use exponential back off.  The message you are seeing is each the interval between each reconnect attempt.

**Comment by rohanKanojia** [comment]
@rhuss : Can we close this issue? Or is there anything else left to be done in order to resolve this?

**Comment by rhuss** [comment]
I would like to see that 'exponential back off' message not being logged at level INFO as this is a technical debug information, not useful for a regular user at all.

However, not sure whether this is a f-m-p or a kubernetes-client issue.

**Comment by rohanKanojia** [comment]
Okay, so can we close it after we upgrade to the latest kubernetes client, since your [pullRequest#1140](https://github.com/fabric8io/kubernetes-client/pull/1040) has been merged.
I think this issue is due to the slower s2i build on latest Openshift versions.

**Comment by piyush1594** [comment]
@rhuss I think this is because of client and I think you sent the PR for this to the client. It will be soon fixed as we upgrade client. Second PR is https://github.com/fabric8io/kubernetes-client/pull/1051 which will fix the exception

**Comment by rhuss** [comment]
we then can close this issue (and reopen it in case)
